apiVersion: v1
kind: Service
metadata:
  name: websocket-server
spec:
  selector:
    camel.apache.org/integration: websocket-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
